-- ============================================================================
-- v47 — Report Annuale T12: testi parametrici sezione "L'andamento del programma"
-- ============================================================================
-- Seed dei testi in pricing_settings (v2) così sono editabili da Listino v2.
-- NON sovrascrive eventuali override già presenti (ON CONFLICT DO NOTHING).
-- Rete di sicurezza: se un testo manca, il report usa il default nel codice
-- (lib/pricing/settings.js → ANDAMENTO_T12_DEFAULTS). Questo seed = quei default.
-- ============================================================================

INSERT INTO public.pricing_settings (version, key, value) VALUES
  ('v2', 'report_t12_andamento_titolo', '## L''andamento del programma'),
  ('v2', 'report_t12_andamento_intro', 'La salute muscolo-scheletrica della popolazione è stata rilevata con la stessa strumentazione a due momenti: all''avvio del programma ({t0N} questionari) e a dodici mesi ({t12N} questionari). Le due rilevazioni riguardano coorti in parte diverse: il confronto è quindi condotto sulle prevalenze — la quota di popolazione in ciascun livello — e non sui conteggi assoluti. La coorte ri-valutata a dodici mesi copre il {ratioPct}% di quella iniziale. I dati che seguono sono aggregati e non riferibili a singoli dipendenti.'),
  ('v2', 'report_t12_andamento_a_vantaggio', '**Rispetto al settore.** La prevalenza di Livello 1 — dipendenti con dolore muscolo-scheletrico e impatto funzionale, quindi con necessità di trattamento — osservata {aPoint} è del {obsPct}%, a fronte di un valore medio atteso di settore del {midPct}% per un''azienda che non attua interventi dedicati. La popolazione si colloca {gapPts} punti percentuali al di sotto dell''atteso: un profilo di salute più favorevole del riferimento di settore.'),
  ('v2', 'report_t12_andamento_a_pari_sopra', '**Rispetto al settore.** La prevalenza di Livello 1 — dipendenti con dolore muscolo-scheletrico e impatto funzionale — osservata {aPoint} è del {obsPct}%, a fronte di un valore medio atteso di settore del {midPct}%. Su questo indicatore la popolazione non presenta un vantaggio rispetto al riferimento di settore: è l''area prioritaria su cui concentrare il programma nell''anno successivo, a partire dai dipendenti che necessitano di trattamento.'),
  ('v2', 'report_t12_andamento_b_riduzione', '**Andamento nei dodici mesi.** Sulla coorte ri-valutata — pari al {ratioPct}% delle persone esaminate all''avvio, quota sufficiente a rendere il confronto rappresentativo — la prevalenza di Livello 1 è passata dal {t0L1pct}% al {t12L1pct}%, con una riduzione di {deltaAbs} punti percentuali. È il risultato osservato al termine del primo anno: una quota inferiore di dipendenti con dolore e impatto funzionale rispetto all''avvio.'),
  ('v2', 'report_t12_andamento_b_stabile', '**Andamento nei dodici mesi.** Sulla coorte ri-valutata — pari al {ratioPct}% delle persone esaminate all''avvio — la prevalenza di Livello 1 si è mantenuta stabile, dal {t0L1pct}% all''avvio al {t12L1pct}% a dodici mesi. Il mantenimento del quadro nell''arco dell''anno è coerente con l''obiettivo del programma, che punta a prevenire il deterioramento della salute muscolo-scheletrica nel tempo: è un esito, non un''assenza di risultato.'),
  ('v2', 'report_t12_andamento_b_aumento', '**Andamento nei dodici mesi.** Sulla coorte ri-valutata — pari al {ratioPct}% delle persone esaminate all''avvio — la prevalenza di Livello 1 è aumentata, dal {t0L1pct}% al {t12L1pct}% a dodici mesi, con un incremento di {deltaAbs} punti percentuali. Il dato è riportato con trasparenza: nell''anno considerato la quota di dipendenti con dolore e impatto funzionale è cresciuta. È l''area prioritaria su cui concentrare trattamenti mirati e monitoraggio nel ciclo successivo.'),
  ('v2', 'report_t12_andamento_b_coorte_parziale', '**Andamento nei dodici mesi (dato indicativo).** A dodici mesi è stato ri-valutato il {ratioPct}% delle persone esaminate all''avvio ({t12N} su {t0N}), una quota inferiore alla soglia del 70% che rende il confronto rappresentativo dell''intera popolazione. La variazione anno-su-anno va quindi letta come indicazione e non come risultato consolidato: sulla coorte disponibile la prevalenza di Livello 1 è del {t12L1pct}%, contro il {t0L1pct}% all''avvio. La lettura di riferimento resta il confronto con il valore atteso di settore riportato sopra.'),
  ('v2', 'report_t12_andamento_degrado_kanon', '**Confronto non esprimibile in percentuale.** All''avvio sono stati raccolti {t0N} questionari e a dodici mesi {t12N}. Per almeno una delle due rilevazioni la numerosità è inferiore alla soglia minima di {kMin} persone: su gruppi così piccoli una prevalenza percentuale non può essere al tempo stesso rappresentativa e rispettosa dell''anonimato dei singoli dipendenti, e per questo non viene riportata. Non si tratta di un dato mancante, ma di una tutela prevista per le popolazioni di piccole dimensioni. Il programma prosegue con la stessa strumentazione e i confronti percentuali diventeranno disponibili al crescere delle persone valutate.'),
  ('v2', 'report_t12_andamento_chiusura_rinnovo', '**In sintesi.** A dodici mesi la prevalenza di Livello 1 si mantiene al di sotto del valore atteso di settore ({t12L1pct}% contro {midPct}%), su una coorte di copertura adeguata. Il mantenimento di questo vantaggio di salute muscolo-scheletrica è l''esito che il programma è chiamato a produrre; darne continuità nell''anno successivo è l''investimento che consente di preservare il risultato nel tempo, più che un intervento correttivo a posteriori.'),
  ('v2', 'report_t12_andamento_chiusura_consolidamento', '**In sintesi.** L''indicazione di quest''anno è un aumento della prevalenza di Livello 1, da leggere con trasparenza come area prioritaria di lavoro. Il programma dell''anno successivo va orientato a intercettare i dipendenti con dolore e impatto funzionale e a riportare la prevalenza verso e sotto il valore atteso di settore, rafforzando la continuità del monitoraggio e dei trattamenti.'),
  ('v2', 'report_t12_andamento_chiusura_neutra', '**In sintesi.** I dati di quest''anno costituiscono la base di misura, verificabile e confrontabile, su cui impostare il lavoro dell''anno successivo. La continuità della stessa strumentazione consente di consolidare i risultati dove presenti e di intervenire sulle aree in cui la prevalenza di Livello 1 resta da ridurre, sempre nel rispetto dell''anonimato dei dipendenti.')
ON CONFLICT (version, key) DO NOTHING;
